# fly.toml app configuration file generated for minecraft-discord-bot on 2023-06-21T11:47:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minecraft-discord-bot"
primary_region = "hkg"
kill_signal = "SIGINT"
[build]
builtin = "python"
[experimental]
allowed_public_ports = []
auto_rollback = ture
[[services]]
internal_port = 8080
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"