# fly.toml app configuration file generated for minecraft-discord-bot on 2023-06-21T11:47:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minecraft-discord-bot"
primary_region = "hkg"

[processes]
file = "/bot/temp_file"
bot = "/bot"

[http_service]
  processes = ["file"]
  internal_port = 1346
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

[[services]]
  processes = ["file"] # this service only applies to the web process
  http_checks = []
  internal_port = 1346
  protocol = "http"
  script_checks = []

[[services]]
  processes = ["bot"] # this service only applies to the web process
  http_checks = []
  internal_port = 8080
  protocol = "http"
  script_checks = []