# fly.toml app configuration file generated for minecraft-discord-bot on 2023-06-21T11:47:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minecraft-discord-bot"
primary_region = "hkg"

[processes]
file = "/bot/temp_file/file_server.py"
bot = "/bot/bot.py"


[http_service]
  processes = ["bot"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  protocol = "https"
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250